#!/usr/bin/env perl
use strict;
use warnings;
use 5.014;
use File::Copy;

die "Filename not found!\n" if @ARGV == 0;

my $data = "";
$data .= $_  for(<DATA>);
foreach my $filename(@ARGV){
	die "File $filename already exist!\n" if -e $filename;
	open (my $file, ">$filename") or die "not open $filename :-(\n$!";
	print $file $data;
	chmod 0777, $filename;
} 

__DATA__
#!/usr/bin/env perl
use 5.014;
use strict;
use warnings;
use utf8;
use open qw/:encoding(UTF-8) :std/;



