#!/usr/bin/env perl
use 5.014;
use strict;
use warnings;
use utf8;
use open qw/:encoding(UTF-8) :std/;
use Tk;
use Schedule::Cron;

open STDOUT, "/dev/null";
#die if `ps -u $ENV{USER}` ~~ /Schedule/;

my $cron = Schedule::Cron-> new(sub{});
$cron->add_entry("*/21 * * * *", \&minimaze_window, -loglevel => 3);
$cron->run;

sub minimaze_window{
	system "wmctrl -k on";
	my $mw = MainWindow->new;
	$mw->geometry("300x100");
	$mw->title("Caring for your eyes");
        
	$mw->Label(-text => 'You need in break(rule 20/20/20/20)')->pack();    
    
	$mw->Button(-text => "Close", -command =>sub{exit})->pack();
	
	$mw->after(300_000, sub{exit});
      
	MainLoop;
}
