#!/usr/bin/env perl
use 5.014;
use strict;
use warnings;
use utf8;
use open qw/:encoding(UTF-8) :std/;
use LWP::UserAgent;
use Getopt::Long;
use Encode;
#
#This script translate text(from STDIN) from russian to english or conversely
#parameters: -l[destination language] -k[path_2_yandex_translation_key]
#destination_language = ru or en; 
#example of usage: echo "Hello, World!" | ./translate -f en -t ru -k your_yandex_translation_key
#

my ($from_language, $to_language, $key);
GetOptions("f=s" => \$from_language, "t=s" => \$to_language, "k=s" => \$key);
my $language = "$from_language-$to_language";

my $userAgent = LWP::UserAgent->new(agent => 'perl post');

while(<>) {
   my $url = "https://translate.yandex.net/api/v1.5/tr/translate?key=$key&text=$_&lang=$language";
   my $response = $userAgent->post($url);
   say $response->error_as_HTML unless $response->is_success;
   $response->as_string =~ m{<text>(.*)</text>}s;
   my $text = $1;
   $text = decode("utf8", $text);
   print $text;
}


