#!/usr/bin/env perl
use 5.014;
use strict;
use warnings;
use utf8;
use open qw/:encoding(UTF-8) :std/;
use LWP::UserAgent;
use Getopt::Long;
use Encode;
#
#This script translate text(from STDIN) from russian to english or conversely
#parameters: -l[destination language]  
#destination_language = ru or en; 
#example: echo "Hello, World!" | ./translate -l ru
#

my $language;
my %langs = (ru => "en-", en => "ru-");
GetOptions("l=s" => \$language);
$language = $langs{$language}.$language;

my $key_file_path = "$ENV{HOME}/Documents/Keys/yandex_translate_key.txt";
open(my $key_file, $key_file_path) or die "I can't open key_file";
my $key = <$key_file>;
chomp $key;
my $userAgent = LWP::UserAgent->new(agent => 'perl post');

while(<>) {
   my $url = "https://translate.yandex.net/api/v1.5/tr/translate?key=$key&text=$_&lang=$language";
   my $response = $userAgent->post($url);
   say $response->error_as_HTML unless $response->is_success;
   $response->as_string =~ m{<text>(.*)</text>}s;
   my $text = $1;
   $text = decode("utf8", $text);
   print $text;
}


